---
- name: Playbook 1 for Catalyst 9K in Devnet Sandbox
  connection: network_cli
  hosts: switches
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Configure VLAN 10 - 20 - 30
      cisco.ios.ios_vlans:
        config:
          - name: VLAN--10-DATA
            vlan_id: 10
            state: active
            shutdown: disabled
          - name: VLAN--20-DATA
            vlan_id: 20
            state: active
            shutdown: disabled
          - name: VLAN--30-DATA
            vlan_id: 30
            state: active
            shutdown: disabled
        state: merged

    - name: Configure first interfaces 11/12/13
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/11
            mode: access
            access:
              vlan: 10
          - name: GigabitEthernet1/0/12
            mode: access
            access:
              vlan: 20
          - name: GigabitEthernet1/0/13
            mode: access
            access:
              vlan: 20
        state: merged
...
